name: Python CI/CD

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The runner is Ubuntu, an operating system

    steps:
      # Step 1: Checkout code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2  # This gets your code from GitHub

      # Step 2: Set up Python (to run your Python app)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Using Python 3.9 for your app

      # Step 3: Install dependencies (flask in this case)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask  # Install Flask web framework

      # Step 4: Build the Docker image (we’ll build it here)
      - name: Build Docker image
        run: docker build -t my-app .  # Builds your Docker image

      # Step 5: Log in to Docker Hub (this is using GitHub secrets)
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin  # Log in to Docker Hub with your credentials

      # Step 6: Push the Docker image to Docker Hub (we push it here)
      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Tag the image with your Docker Hub username
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Push the image to Docker Hub
    
